name: ctapipe-io-hess
channels:
  - conda-forge
dependencies:
  - python=3.13
  - ipykernel
  - pip
  - black
  - ctapipe=0.26
  - matplotlib
  - pytest
  - uproot
  - pre-commit
  - pydata-sphinx-theme
  - sphinx
  - sphinx_changelog
  - numpydoc
  - nbsphinx
  - ipywidgets
